coverage:
  status:
    project:
      default:
        target: 10%
      backend:
        flags: [backend]
      frontend:
        flags: [frontend]
        target: 10%
    patch: off

flags:
  backend:
    paths:
      - internal/
      - pkg/
      - cmd/
    carryforward: true

  frontend:
    paths:
      - web/src/
    carryforward: true
