// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SdkVersion           string                 `protobuf:"bytes,1,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`                                 // Automatically set by SDK const Version
	PluginId             string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                                       // e.g. "community-manga-pack"
	PluginName           string                 `protobuf:"bytes,3,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`                                 // e.g. "Community Manga Pack"
	PluginVersion        string                 `protobuf:"bytes,4,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`                        // e.g. "1.2.0"
	PluginSettingsSchema []*SettingSpec         `protobuf:"bytes,5,rep,name=plugin_settings_schema,json=pluginSettingsSchema,proto3" json:"plugin_settings_schema,omitempty"` // Global plugin settings
	Providers            []*ProviderDescriptor  `protobuf:"bytes,6,rep,name=providers,proto3" json:"providers,omitempty"`                                                     // Contained providers
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *DescribeResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *DescribeResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *DescribeResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *DescribeResponse) GetPluginSettingsSchema() []*SettingSpec {
	if x != nil {
		return x.PluginSettingsSchema
	}
	return nil
}

func (x *DescribeResponse) GetProviders() []*ProviderDescriptor {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderDescriptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // e.g. "mangadex"
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g. "MangaDex"
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities     []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                           // ["metadata", "content", "tracking"]
	SettingsSchema   []*SettingSpec         `protobuf:"bytes,5,rep,name=settings_schema,json=settingsSchema,proto3" json:"settings_schema,omitempty"` // Scoped to this specific provider ID
	DefaultRateLimit *RateLimitSpec         `protobuf:"bytes,6,opt,name=default_rate_limit,json=defaultRateLimit,proto3" json:"default_rate_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProviderDescriptor) Reset() {
	*x = ProviderDescriptor{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderDescriptor) ProtoMessage() {}

func (x *ProviderDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderDescriptor.ProtoReflect.Descriptor instead.
func (*ProviderDescriptor) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProviderDescriptor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderDescriptor) GetSettingsSchema() []*SettingSpec {
	if x != nil {
		return x.SettingsSchema
	}
	return nil
}

func (x *ProviderDescriptor) GetDefaultRateLimit() *RateLimitSpec {
	if x != nil {
		return x.DefaultRateLimit
	}
	return nil
}

type RateLimitSpec struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond     int32                  `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	MaxConcurrentRequests int32                  `protobuf:"varint,2,opt,name=max_concurrent_requests,json=maxConcurrentRequests,proto3" json:"max_concurrent_requests,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RateLimitSpec) Reset() {
	*x = RateLimitSpec{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitSpec) ProtoMessage() {}

func (x *RateLimitSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitSpec.ProtoReflect.Descriptor instead.
func (*RateLimitSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *RateLimitSpec) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RateLimitSpec) GetMaxConcurrentRequests() int32 {
	if x != nil {
		return x.MaxConcurrentRequests
	}
	return 0
}

type SettingSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "string", "number", "boolean", "secret", "select"
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Options       []string               `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingSpec) Reset() {
	*x = SettingSpec{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingSpec) ProtoMessage() {}

func (x *SettingSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingSpec.ProtoReflect.Descriptor instead.
func (*SettingSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SettingSpec) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SettingSpec) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SettingSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SettingSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SettingSpec) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *SettingSpec) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type InitRequest struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	GlobalConfig    map[string]string             `protobuf:"bytes,1,rep,name=global_config,json=globalConfig,proto3" json:"global_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`          // Shared plugin-wide settings
	ProviderConfigs map[string]*ProviderConfigMap `protobuf:"bytes,2,rep,name=provider_configs,json=providerConfigs,proto3" json:"provider_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Map of provider_id -> { key -> value }
	HttpConfig      *GlobalHttpConfig             `protobuf:"bytes,3,opt,name=http_config,json=httpConfig,proto3" json:"http_config,omitempty"`                                                                                          // System-wide proxy & User-Agent
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *InitRequest) GetGlobalConfig() map[string]string {
	if x != nil {
		return x.GlobalConfig
	}
	return nil
}

func (x *InitRequest) GetProviderConfigs() map[string]*ProviderConfigMap {
	if x != nil {
		return x.ProviderConfigs
	}
	return nil
}

func (x *InitRequest) GetHttpConfig() *GlobalHttpConfig {
	if x != nil {
		return x.HttpConfig
	}
	return nil
}

type ProviderConfigMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value settings for this provider ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfigMap) Reset() {
	*x = ProviderConfigMap{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfigMap) ProtoMessage() {}

func (x *ProviderConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfigMap.ProtoReflect.Descriptor instead.
func (*ProviderConfigMap) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderConfigMap) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GlobalHttpConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProxyUrl       string                 `protobuf:"bytes,1,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	UserAgent      string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	DnsResolvers   []string               `protobuf:"bytes,4,rep,name=dns_resolvers,json=dnsResolvers,proto3" json:"dns_resolvers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GlobalHttpConfig) Reset() {
	*x = GlobalHttpConfig{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalHttpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalHttpConfig) ProtoMessage() {}

func (x *GlobalHttpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalHttpConfig.ProtoReflect.Descriptor instead.
func (*GlobalHttpConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *GlobalHttpConfig) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *GlobalHttpConfig) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *GlobalHttpConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *GlobalHttpConfig) GetDnsResolvers() []string {
	if x != nil {
		return x.DnsResolvers
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteId      string                 `protobuf:"bytes,1,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Aliases       []string               `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Availability  string                 `protobuf:"bytes,6,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *SearchResult) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *SearchResult) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *SearchResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SearchResult) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

type MangaMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteId      string                 `protobuf:"bytes,1,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Aliases       []string               `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Synopsis      string                 `protobuf:"bytes,5,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Author        string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	Artist        string                 `protobuf:"bytes,8,opt,name=artist,proto3" json:"artist,omitempty"`
	Genres        []string               `protobuf:"bytes,9,rep,name=genres,proto3" json:"genres,omitempty"`
	TotalChapters int32                  `protobuf:"varint,10,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	ReadingMode   string                 `protobuf:"bytes,11,opt,name=reading_mode,json=readingMode,proto3" json:"reading_mode,omitempty"`
	Score         float32                `protobuf:"fixed32,12,opt,name=score,proto3" json:"score,omitempty"`
	Url           string                 `protobuf:"bytes,13,opt,name=url,proto3" json:"url,omitempty"`
	Availability  string                 `protobuf:"bytes,14,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaMetadata) Reset() {
	*x = MangaMetadata{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaMetadata) ProtoMessage() {}

func (x *MangaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaMetadata.ProtoReflect.Descriptor instead.
func (*MangaMetadata) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *MangaMetadata) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *MangaMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MangaMetadata) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *MangaMetadata) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *MangaMetadata) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *MangaMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MangaMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MangaMetadata) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *MangaMetadata) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MangaMetadata) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *MangaMetadata) GetReadingMode() string {
	if x != nil {
		return x.ReadingMode
	}
	return ""
}

func (x *MangaMetadata) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MangaMetadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MangaMetadata) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

type ImageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRef) Reset() {
	*x = ImageRef{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRef) ProtoMessage() {}

func (x *ImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRef.ProtoReflect.Descriptor instead.
func (*ImageRef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ImageRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageRef) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageRef) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageRef) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Chapter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url            string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Number         float32                `protobuf:"fixed32,4,opt,name=number,proto3" json:"number,omitempty"`
	UploadDateUnix int64                  `protobuf:"varint,5,opt,name=upload_date_unix,json=uploadDateUnix,proto3" json:"upload_date_unix,omitempty"`
	SourceOrder    int32                  `protobuf:"varint,6,opt,name=source_order,json=sourceOrder,proto3" json:"source_order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Chapter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chapter) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Chapter) GetNumber() float32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Chapter) GetUploadDateUnix() int64 {
	if x != nil {
		return x.UploadDateUnix
	}
	return 0
}

func (x *Chapter) GetSourceOrder() int32 {
	if x != nil {
		return x.SourceOrder
	}
	return 0
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *Page) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Page) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Page) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type RateLimitHint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond float64                `protobuf:"fixed64,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	RequestsPerMinute float64                `protobuf:"fixed64,2,opt,name=requests_per_minute,json=requestsPerMinute,proto3" json:"requests_per_minute,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimitHint) Reset() {
	*x = RateLimitHint{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitHint) ProtoMessage() {}

func (x *RateLimitHint) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitHint.ProtoReflect.Descriptor instead.
func (*RateLimitHint) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *RateLimitHint) GetRequestsPerSecond() float64 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RateLimitHint) GetRequestsPerMinute() float64 {
	if x != nil {
		return x.RequestsPerMinute
	}
	return 0
}

type UserCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCredentials) Reset() {
	*x = UserCredentials{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredentials) ProtoMessage() {}

func (x *UserCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredentials.ProtoReflect.Descriptor instead.
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *UserCredentials) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserCredentials) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserCredentials) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *Session) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Session) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Session) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *Progress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Progress) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Progress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Progress) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *SearchRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	RemoteId      string                 `protobuf:"bytes,2,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailsRequest) Reset() {
	*x = DetailsRequest{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsRequest) ProtoMessage() {}

func (x *DetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsRequest.ProtoReflect.Descriptor instead.
func (*DetailsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *DetailsRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *DetailsRequest) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

type DetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *MangaMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailsResponse) Reset() {
	*x = DetailsResponse{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsResponse) ProtoMessage() {}

func (x *DetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsResponse.ProtoReflect.Descriptor instead.
func (*DetailsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *DetailsResponse) GetMetadata() *MangaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	RemoteId      string                 `protobuf:"bytes,2,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverRequest) Reset() {
	*x = CoverRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverRequest) ProtoMessage() {}

func (x *CoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverRequest.ProtoReflect.Descriptor instead.
func (*CoverRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *CoverRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CoverRequest) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *CoverRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type CoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cover         *ImageRef              `protobuf:"bytes,1,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverResponse) Reset() {
	*x = CoverResponse{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverResponse) ProtoMessage() {}

func (x *CoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverResponse.ProtoReflect.Descriptor instead.
func (*CoverResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *CoverResponse) GetCover() *ImageRef {
	if x != nil {
		return x.Cover
	}
	return nil
}

type AliasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	RemoteId      string                 `protobuf:"bytes,2,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasesRequest) Reset() {
	*x = AliasesRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasesRequest) ProtoMessage() {}

func (x *AliasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasesRequest.ProtoReflect.Descriptor instead.
func (*AliasesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *AliasesRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AliasesRequest) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

type AliasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aliases       []string               `protobuf:"bytes,1,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasesResponse) Reset() {
	*x = AliasesResponse{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasesResponse) ProtoMessage() {}

func (x *AliasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasesResponse.ProtoReflect.Descriptor instead.
func (*AliasesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *AliasesResponse) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type HasStableChapterIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasStableChapterIDRequest) Reset() {
	*x = HasStableChapterIDRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasStableChapterIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasStableChapterIDRequest) ProtoMessage() {}

func (x *HasStableChapterIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasStableChapterIDRequest.ProtoReflect.Descriptor instead.
func (*HasStableChapterIDRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *HasStableChapterIDRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type HasStableChapterIDResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HasStableChapterId bool                   `protobuf:"varint,1,opt,name=has_stable_chapter_id,json=hasStableChapterId,proto3" json:"has_stable_chapter_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HasStableChapterIDResponse) Reset() {
	*x = HasStableChapterIDResponse{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasStableChapterIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasStableChapterIDResponse) ProtoMessage() {}

func (x *HasStableChapterIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasStableChapterIDResponse.ProtoReflect.Descriptor instead.
func (*HasStableChapterIDResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *HasStableChapterIDResponse) GetHasStableChapterId() bool {
	if x != nil {
		return x.HasStableChapterId
	}
	return false
}

type FetchChaptersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	MangaRef      string                 `protobuf:"bytes,2,opt,name=manga_ref,json=mangaRef,proto3" json:"manga_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChaptersRequest) Reset() {
	*x = FetchChaptersRequest{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChaptersRequest) ProtoMessage() {}

func (x *FetchChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChaptersRequest.ProtoReflect.Descriptor instead.
func (*FetchChaptersRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *FetchChaptersRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *FetchChaptersRequest) GetMangaRef() string {
	if x != nil {
		return x.MangaRef
	}
	return ""
}

type FetchChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*Chapter             `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChaptersResponse) Reset() {
	*x = FetchChaptersResponse{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChaptersResponse) ProtoMessage() {}

func (x *FetchChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChaptersResponse.ProtoReflect.Descriptor instead.
func (*FetchChaptersResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *FetchChaptersResponse) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type FetchPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	MangaRef      string                 `protobuf:"bytes,2,opt,name=manga_ref,json=mangaRef,proto3" json:"manga_ref,omitempty"`
	ChapterRef    string                 `protobuf:"bytes,3,opt,name=chapter_ref,json=chapterRef,proto3" json:"chapter_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPagesRequest) Reset() {
	*x = FetchPagesRequest{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPagesRequest) ProtoMessage() {}

func (x *FetchPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPagesRequest.ProtoReflect.Descriptor instead.
func (*FetchPagesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *FetchPagesRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *FetchPagesRequest) GetMangaRef() string {
	if x != nil {
		return x.MangaRef
	}
	return ""
}

func (x *FetchPagesRequest) GetChapterRef() string {
	if x != nil {
		return x.ChapterRef
	}
	return ""
}

type FetchPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPagesResponse) Reset() {
	*x = FetchPagesResponse{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPagesResponse) ProtoMessage() {}

func (x *FetchPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPagesResponse.ProtoReflect.Descriptor instead.
func (*FetchPagesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *FetchPagesResponse) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type FetchPageStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Page          *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPageStreamRequest) Reset() {
	*x = FetchPageStreamRequest{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPageStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPageStreamRequest) ProtoMessage() {}

func (x *FetchPageStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPageStreamRequest.ProtoReflect.Descriptor instead.
func (*FetchPageStreamRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *FetchPageStreamRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *FetchPageStreamRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type FetchPageStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPageStreamResponse) Reset() {
	*x = FetchPageStreamResponse{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPageStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPageStreamResponse) ProtoMessage() {}

func (x *FetchPageStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPageStreamResponse.ProtoReflect.Descriptor instead.
func (*FetchPageStreamResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *FetchPageStreamResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type RateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *RateLimitRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RateLimit     *RateLimitHint         `protobuf:"bytes,1,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *RateLimitResponse) GetRateLimit() *RateLimitHint {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Credentials   *UserCredentials       `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *AuthenticateRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AuthenticateRequest) GetCredentials() *UserCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{37}
}

func (x *AuthenticateResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type PushProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	RemoteId      string                 `protobuf:"bytes,2,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushProgressRequest) Reset() {
	*x = PushProgressRequest{}
	mi := &file_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushProgressRequest) ProtoMessage() {}

func (x *PushProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushProgressRequest.ProtoReflect.Descriptor instead.
func (*PushProgressRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{38}
}

func (x *PushProgressRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *PushProgressRequest) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *PushProgressRequest) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type PushProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushProgressResponse) Reset() {
	*x = PushProgressResponse{}
	mi := &file_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushProgressResponse) ProtoMessage() {}

func (x *PushProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushProgressResponse.ProtoReflect.Descriptor instead.
func (*PushProgressResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{39}
}

func (x *PushProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FetchProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	RemoteId      string                 `protobuf:"bytes,2,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchProgressRequest) Reset() {
	*x = FetchProgressRequest{}
	mi := &file_plugin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProgressRequest) ProtoMessage() {}

func (x *FetchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProgressRequest.ProtoReflect.Descriptor instead.
func (*FetchProgressRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{40}
}

func (x *FetchProgressRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *FetchProgressRequest) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

type FetchProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *Progress              `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchProgressResponse) Reset() {
	*x = FetchProgressResponse{}
	mi := &file_plugin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProgressResponse) ProtoMessage() {}

func (x *FetchProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProgressResponse.ProtoReflect.Descriptor instead.
func (*FetchProgressResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{41}
}

func (x *FetchProgressResponse) GetProgress() *Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type IsAuthenticatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAuthenticatedRequest) Reset() {
	*x = IsAuthenticatedRequest{}
	mi := &file_plugin_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAuthenticatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAuthenticatedRequest) ProtoMessage() {}

func (x *IsAuthenticatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAuthenticatedRequest.ProtoReflect.Descriptor instead.
func (*IsAuthenticatedRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{42}
}

func (x *IsAuthenticatedRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type IsAuthenticatedResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsAuthenticated bool                   `protobuf:"varint,1,opt,name=is_authenticated,json=isAuthenticated,proto3" json:"is_authenticated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsAuthenticatedResponse) Reset() {
	*x = IsAuthenticatedResponse{}
	mi := &file_plugin_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAuthenticatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAuthenticatedResponse) ProtoMessage() {}

func (x *IsAuthenticatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAuthenticatedResponse.ProtoReflect.Descriptor instead.
func (*IsAuthenticatedResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{43}
}

func (x *IsAuthenticatedResponse) GetIsAuthenticated() bool {
	if x != nil {
		return x.IsAuthenticated
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x10kiyomi.plugin.v1\"\x11\n" +
	"\x0fDescribeRequest\"\xb1\x02\n" +
	"\x10DescribeResponse\x12\x1f\n" +
	"\vsdk_version\x18\x01 \x01(\tR\n" +
	"sdkVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vplugin_name\x18\x03 \x01(\tR\n" +
	"pluginName\x12%\n" +
	"\x0eplugin_version\x18\x04 \x01(\tR\rpluginVersion\x12S\n" +
	"\x16plugin_settings_schema\x18\x05 \x03(\v2\x1d.kiyomi.plugin.v1.SettingSpecR\x14pluginSettingsSchema\x12B\n" +
	"\tproviders\x18\x06 \x03(\v2$.kiyomi.plugin.v1.ProviderDescriptorR\tproviders\"\x95\x02\n" +
	"\x12ProviderDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12F\n" +
	"\x0fsettings_schema\x18\x05 \x03(\v2\x1d.kiyomi.plugin.v1.SettingSpecR\x0esettingsSchema\x12M\n" +
	"\x12default_rate_limit\x18\x06 \x01(\v2\x1f.kiyomi.plugin.v1.RateLimitSpecR\x10defaultRateLimit\"w\n" +
	"\rRateLimitSpec\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\x126\n" +
	"\x17max_concurrent_requests\x18\x02 \x01(\x05R\x15maxConcurrentRequests\"\xaa\x01\n" +
	"\vSettingSpec\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\x12\x18\n" +
	"\aoptions\x18\x06 \x03(\tR\aoptions\"\xb1\x03\n" +
	"\vInitRequest\x12T\n" +
	"\rglobal_config\x18\x01 \x03(\v2/.kiyomi.plugin.v1.InitRequest.GlobalConfigEntryR\fglobalConfig\x12]\n" +
	"\x10provider_configs\x18\x02 \x03(\v22.kiyomi.plugin.v1.InitRequest.ProviderConfigsEntryR\x0fproviderConfigs\x12C\n" +
	"\vhttp_config\x18\x03 \x01(\v2\".kiyomi.plugin.v1.GlobalHttpConfigR\n" +
	"httpConfig\x1a?\n" +
	"\x11GlobalConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ag\n" +
	"\x14ProviderConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.kiyomi.plugin.v1.ProviderConfigMapR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x11ProviderConfigMap\x12M\n" +
	"\bsettings\x18\x01 \x03(\v21.kiyomi.plugin.v1.ProviderConfigMap.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\x10GlobalHttpConfig\x12\x1b\n" +
	"\tproxy_url\x18\x01 \x01(\tR\bproxyUrl\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12#\n" +
	"\rdns_resolvers\x18\x04 \x03(\tR\fdnsResolvers\"M\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xae\x01\n" +
	"\fSearchResult\x12\x1b\n" +
	"\tremote_id\x18\x01 \x01(\tR\bremoteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\"\n" +
	"\favailability\x18\x06 \x01(\tR\favailability\"\x8b\x03\n" +
	"\rMangaMetadata\x12\x1b\n" +
	"\tremote_id\x18\x01 \x01(\tR\bremoteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bsynopsis\x18\x05 \x01(\tR\bsynopsis\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x16\n" +
	"\x06artist\x18\b \x01(\tR\x06artist\x12\x16\n" +
	"\x06genres\x18\t \x03(\tR\x06genres\x12%\n" +
	"\x0etotal_chapters\x18\n" +
	" \x01(\x05R\rtotalChapters\x12!\n" +
	"\freading_mode\x18\v \x01(\tR\vreadingMode\x12\x14\n" +
	"\x05score\x18\f \x01(\x02R\x05score\x12\x10\n" +
	"\x03url\x18\r \x01(\tR\x03url\x12\"\n" +
	"\favailability\x18\x0e \x01(\tR\favailability\"\xe6\x01\n" +
	"\bImageRef\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12A\n" +
	"\aheaders\x18\x05 \x03(\v2'.kiyomi.plugin.v1.ImageRef.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\aChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x02R\x06number\x12(\n" +
	"\x10upload_date_unix\x18\x05 \x01(\x03R\x0euploadDateUnix\x12!\n" +
	"\fsource_order\x18\x06 \x01(\x05R\vsourceOrder\"\xa9\x01\n" +
	"\x04Page\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12=\n" +
	"\aheaders\x18\x03 \x03(\v2#.kiyomi.plugin.v1.Page.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\rRateLimitHint\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x01R\x11requestsPerSecond\x12.\n" +
	"\x13requests_per_minute\x18\x02 \x01(\x01R\x11requestsPerMinute\"\x81\x01\n" +
	"\x0fUserCredentials\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\"\x92\x01\n" +
	"\aSession\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"|\n" +
	"\bProgress\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnix\"\x88\x01\n" +
	"\rSearchRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\"J\n" +
	"\x0eSearchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.kiyomi.plugin.v1.SearchResultR\aresults\"N\n" +
	"\x0eDetailsRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tremote_id\x18\x02 \x01(\tR\bremoteId\"N\n" +
	"\x0fDetailsResponse\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.kiyomi.plugin.v1.MangaMetadataR\bmetadata\"`\n" +
	"\fCoverRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tremote_id\x18\x02 \x01(\tR\bremoteId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\"A\n" +
	"\rCoverResponse\x120\n" +
	"\x05cover\x18\x01 \x01(\v2\x1a.kiyomi.plugin.v1.ImageRefR\x05cover\"N\n" +
	"\x0eAliasesRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tremote_id\x18\x02 \x01(\tR\bremoteId\"+\n" +
	"\x0fAliasesResponse\x12\x18\n" +
	"\aaliases\x18\x01 \x03(\tR\aaliases\"<\n" +
	"\x19HasStableChapterIDRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"O\n" +
	"\x1aHasStableChapterIDResponse\x121\n" +
	"\x15has_stable_chapter_id\x18\x01 \x01(\bR\x12hasStableChapterId\"T\n" +
	"\x14FetchChaptersRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tmanga_ref\x18\x02 \x01(\tR\bmangaRef\"N\n" +
	"\x15FetchChaptersResponse\x125\n" +
	"\bchapters\x18\x01 \x03(\v2\x19.kiyomi.plugin.v1.ChapterR\bchapters\"r\n" +
	"\x11FetchPagesRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tmanga_ref\x18\x02 \x01(\tR\bmangaRef\x12\x1f\n" +
	"\vchapter_ref\x18\x03 \x01(\tR\n" +
	"chapterRef\"B\n" +
	"\x12FetchPagesResponse\x12,\n" +
	"\x05pages\x18\x01 \x03(\v2\x16.kiyomi.plugin.v1.PageR\x05pages\"e\n" +
	"\x16FetchPageStreamRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.kiyomi.plugin.v1.PageR\x04page\"/\n" +
	"\x17FetchPageStreamResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"3\n" +
	"\x10RateLimitRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"S\n" +
	"\x11RateLimitResponse\x12>\n" +
	"\n" +
	"rate_limit\x18\x01 \x01(\v2\x1f.kiyomi.plugin.v1.RateLimitHintR\trateLimit\"{\n" +
	"\x13AuthenticateRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12C\n" +
	"\vcredentials\x18\x02 \x01(\v2!.kiyomi.plugin.v1.UserCredentialsR\vcredentials\"K\n" +
	"\x14AuthenticateResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.kiyomi.plugin.v1.SessionR\asession\"o\n" +
	"\x13PushProgressRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tremote_id\x18\x02 \x01(\tR\bremoteId\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\"0\n" +
	"\x14PushProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x14FetchProgressRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tremote_id\x18\x02 \x01(\tR\bremoteId\"O\n" +
	"\x15FetchProgressResponse\x126\n" +
	"\bprogress\x18\x01 \x01(\v2\x1a.kiyomi.plugin.v1.ProgressR\bprogress\"9\n" +
	"\x16IsAuthenticatedRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"D\n" +
	"\x17IsAuthenticatedResponse\x12)\n" +
	"\x10is_authenticated\x18\x01 \x01(\bR\x0fisAuthenticated2\xa9\x01\n" +
	"\rPluginService\x12Q\n" +
	"\bDescribe\x12!.kiyomi.plugin.v1.DescribeRequest\x1a\".kiyomi.plugin.v1.DescribeResponse\x12E\n" +
	"\x04Init\x12\x1d.kiyomi.plugin.v1.InitRequest\x1a\x1e.kiyomi.plugin.v1.InitResponse2\xd0\x02\n" +
	"\x17MetadataProviderService\x12K\n" +
	"\x06Search\x12\x1f.kiyomi.plugin.v1.SearchRequest\x1a .kiyomi.plugin.v1.SearchResponse\x12N\n" +
	"\aDetails\x12 .kiyomi.plugin.v1.DetailsRequest\x1a!.kiyomi.plugin.v1.DetailsResponse\x12H\n" +
	"\x05Cover\x12\x1e.kiyomi.plugin.v1.CoverRequest\x1a\x1f.kiyomi.plugin.v1.CoverResponse\x12N\n" +
	"\aAliases\x12 .kiyomi.plugin.v1.AliasesRequest\x1a!.kiyomi.plugin.v1.AliasesResponse2\x84\x04\n" +
	"\x16ContentProviderService\x12o\n" +
	"\x12HasStableChapterID\x12+.kiyomi.plugin.v1.HasStableChapterIDRequest\x1a,.kiyomi.plugin.v1.HasStableChapterIDResponse\x12`\n" +
	"\rFetchChapters\x12&.kiyomi.plugin.v1.FetchChaptersRequest\x1a'.kiyomi.plugin.v1.FetchChaptersResponse\x12W\n" +
	"\n" +
	"FetchPages\x12#.kiyomi.plugin.v1.FetchPagesRequest\x1a$.kiyomi.plugin.v1.FetchPagesResponse\x12h\n" +
	"\x0fFetchPageStream\x12(.kiyomi.plugin.v1.FetchPageStreamRequest\x1a).kiyomi.plugin.v1.FetchPageStreamResponse0\x01\x12T\n" +
	"\tRateLimit\x12\".kiyomi.plugin.v1.RateLimitRequest\x1a#.kiyomi.plugin.v1.RateLimitResponse2\x98\x03\n" +
	"\x0eTrackerService\x12]\n" +
	"\fAuthenticate\x12%.kiyomi.plugin.v1.AuthenticateRequest\x1a&.kiyomi.plugin.v1.AuthenticateResponse\x12]\n" +
	"\fPushProgress\x12%.kiyomi.plugin.v1.PushProgressRequest\x1a&.kiyomi.plugin.v1.PushProgressResponse\x12`\n" +
	"\rFetchProgress\x12&.kiyomi.plugin.v1.FetchProgressRequest\x1a'.kiyomi.plugin.v1.FetchProgressResponse\x12f\n" +
	"\x0fIsAuthenticated\x12(.kiyomi.plugin.v1.IsAuthenticatedRequest\x1a).kiyomi.plugin.v1.IsAuthenticatedResponseB1Z/github.com/tubruk/kiyomi/plugin-sdk/proto/v1;v1b\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_plugin_proto_goTypes = []any{
	(*DescribeRequest)(nil),            // 0: kiyomi.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),           // 1: kiyomi.plugin.v1.DescribeResponse
	(*ProviderDescriptor)(nil),         // 2: kiyomi.plugin.v1.ProviderDescriptor
	(*RateLimitSpec)(nil),              // 3: kiyomi.plugin.v1.RateLimitSpec
	(*SettingSpec)(nil),                // 4: kiyomi.plugin.v1.SettingSpec
	(*InitRequest)(nil),                // 5: kiyomi.plugin.v1.InitRequest
	(*ProviderConfigMap)(nil),          // 6: kiyomi.plugin.v1.ProviderConfigMap
	(*GlobalHttpConfig)(nil),           // 7: kiyomi.plugin.v1.GlobalHttpConfig
	(*InitResponse)(nil),               // 8: kiyomi.plugin.v1.InitResponse
	(*SearchResult)(nil),               // 9: kiyomi.plugin.v1.SearchResult
	(*MangaMetadata)(nil),              // 10: kiyomi.plugin.v1.MangaMetadata
	(*ImageRef)(nil),                   // 11: kiyomi.plugin.v1.ImageRef
	(*Chapter)(nil),                    // 12: kiyomi.plugin.v1.Chapter
	(*Page)(nil),                       // 13: kiyomi.plugin.v1.Page
	(*RateLimitHint)(nil),              // 14: kiyomi.plugin.v1.RateLimitHint
	(*UserCredentials)(nil),            // 15: kiyomi.plugin.v1.UserCredentials
	(*Session)(nil),                    // 16: kiyomi.plugin.v1.Session
	(*Progress)(nil),                   // 17: kiyomi.plugin.v1.Progress
	(*SearchRequest)(nil),              // 18: kiyomi.plugin.v1.SearchRequest
	(*SearchResponse)(nil),             // 19: kiyomi.plugin.v1.SearchResponse
	(*DetailsRequest)(nil),             // 20: kiyomi.plugin.v1.DetailsRequest
	(*DetailsResponse)(nil),            // 21: kiyomi.plugin.v1.DetailsResponse
	(*CoverRequest)(nil),               // 22: kiyomi.plugin.v1.CoverRequest
	(*CoverResponse)(nil),              // 23: kiyomi.plugin.v1.CoverResponse
	(*AliasesRequest)(nil),             // 24: kiyomi.plugin.v1.AliasesRequest
	(*AliasesResponse)(nil),            // 25: kiyomi.plugin.v1.AliasesResponse
	(*HasStableChapterIDRequest)(nil),  // 26: kiyomi.plugin.v1.HasStableChapterIDRequest
	(*HasStableChapterIDResponse)(nil), // 27: kiyomi.plugin.v1.HasStableChapterIDResponse
	(*FetchChaptersRequest)(nil),       // 28: kiyomi.plugin.v1.FetchChaptersRequest
	(*FetchChaptersResponse)(nil),      // 29: kiyomi.plugin.v1.FetchChaptersResponse
	(*FetchPagesRequest)(nil),          // 30: kiyomi.plugin.v1.FetchPagesRequest
	(*FetchPagesResponse)(nil),         // 31: kiyomi.plugin.v1.FetchPagesResponse
	(*FetchPageStreamRequest)(nil),     // 32: kiyomi.plugin.v1.FetchPageStreamRequest
	(*FetchPageStreamResponse)(nil),    // 33: kiyomi.plugin.v1.FetchPageStreamResponse
	(*RateLimitRequest)(nil),           // 34: kiyomi.plugin.v1.RateLimitRequest
	(*RateLimitResponse)(nil),          // 35: kiyomi.plugin.v1.RateLimitResponse
	(*AuthenticateRequest)(nil),        // 36: kiyomi.plugin.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),       // 37: kiyomi.plugin.v1.AuthenticateResponse
	(*PushProgressRequest)(nil),        // 38: kiyomi.plugin.v1.PushProgressRequest
	(*PushProgressResponse)(nil),       // 39: kiyomi.plugin.v1.PushProgressResponse
	(*FetchProgressRequest)(nil),       // 40: kiyomi.plugin.v1.FetchProgressRequest
	(*FetchProgressResponse)(nil),      // 41: kiyomi.plugin.v1.FetchProgressResponse
	(*IsAuthenticatedRequest)(nil),     // 42: kiyomi.plugin.v1.IsAuthenticatedRequest
	(*IsAuthenticatedResponse)(nil),    // 43: kiyomi.plugin.v1.IsAuthenticatedResponse
	nil,                                // 44: kiyomi.plugin.v1.InitRequest.GlobalConfigEntry
	nil,                                // 45: kiyomi.plugin.v1.InitRequest.ProviderConfigsEntry
	nil,                                // 46: kiyomi.plugin.v1.ProviderConfigMap.SettingsEntry
	nil,                                // 47: kiyomi.plugin.v1.ImageRef.HeadersEntry
	nil,                                // 48: kiyomi.plugin.v1.Page.HeadersEntry
}
var file_plugin_proto_depIdxs = []int32{
	4,  // 0: kiyomi.plugin.v1.DescribeResponse.plugin_settings_schema:type_name -> kiyomi.plugin.v1.SettingSpec
	2,  // 1: kiyomi.plugin.v1.DescribeResponse.providers:type_name -> kiyomi.plugin.v1.ProviderDescriptor
	4,  // 2: kiyomi.plugin.v1.ProviderDescriptor.settings_schema:type_name -> kiyomi.plugin.v1.SettingSpec
	3,  // 3: kiyomi.plugin.v1.ProviderDescriptor.default_rate_limit:type_name -> kiyomi.plugin.v1.RateLimitSpec
	44, // 4: kiyomi.plugin.v1.InitRequest.global_config:type_name -> kiyomi.plugin.v1.InitRequest.GlobalConfigEntry
	45, // 5: kiyomi.plugin.v1.InitRequest.provider_configs:type_name -> kiyomi.plugin.v1.InitRequest.ProviderConfigsEntry
	7,  // 6: kiyomi.plugin.v1.InitRequest.http_config:type_name -> kiyomi.plugin.v1.GlobalHttpConfig
	46, // 7: kiyomi.plugin.v1.ProviderConfigMap.settings:type_name -> kiyomi.plugin.v1.ProviderConfigMap.SettingsEntry
	47, // 8: kiyomi.plugin.v1.ImageRef.headers:type_name -> kiyomi.plugin.v1.ImageRef.HeadersEntry
	48, // 9: kiyomi.plugin.v1.Page.headers:type_name -> kiyomi.plugin.v1.Page.HeadersEntry
	9,  // 10: kiyomi.plugin.v1.SearchResponse.results:type_name -> kiyomi.plugin.v1.SearchResult
	10, // 11: kiyomi.plugin.v1.DetailsResponse.metadata:type_name -> kiyomi.plugin.v1.MangaMetadata
	11, // 12: kiyomi.plugin.v1.CoverResponse.cover:type_name -> kiyomi.plugin.v1.ImageRef
	12, // 13: kiyomi.plugin.v1.FetchChaptersResponse.chapters:type_name -> kiyomi.plugin.v1.Chapter
	13, // 14: kiyomi.plugin.v1.FetchPagesResponse.pages:type_name -> kiyomi.plugin.v1.Page
	13, // 15: kiyomi.plugin.v1.FetchPageStreamRequest.page:type_name -> kiyomi.plugin.v1.Page
	14, // 16: kiyomi.plugin.v1.RateLimitResponse.rate_limit:type_name -> kiyomi.plugin.v1.RateLimitHint
	15, // 17: kiyomi.plugin.v1.AuthenticateRequest.credentials:type_name -> kiyomi.plugin.v1.UserCredentials
	16, // 18: kiyomi.plugin.v1.AuthenticateResponse.session:type_name -> kiyomi.plugin.v1.Session
	17, // 19: kiyomi.plugin.v1.FetchProgressResponse.progress:type_name -> kiyomi.plugin.v1.Progress
	6,  // 20: kiyomi.plugin.v1.InitRequest.ProviderConfigsEntry.value:type_name -> kiyomi.plugin.v1.ProviderConfigMap
	0,  // 21: kiyomi.plugin.v1.PluginService.Describe:input_type -> kiyomi.plugin.v1.DescribeRequest
	5,  // 22: kiyomi.plugin.v1.PluginService.Init:input_type -> kiyomi.plugin.v1.InitRequest
	18, // 23: kiyomi.plugin.v1.MetadataProviderService.Search:input_type -> kiyomi.plugin.v1.SearchRequest
	20, // 24: kiyomi.plugin.v1.MetadataProviderService.Details:input_type -> kiyomi.plugin.v1.DetailsRequest
	22, // 25: kiyomi.plugin.v1.MetadataProviderService.Cover:input_type -> kiyomi.plugin.v1.CoverRequest
	24, // 26: kiyomi.plugin.v1.MetadataProviderService.Aliases:input_type -> kiyomi.plugin.v1.AliasesRequest
	26, // 27: kiyomi.plugin.v1.ContentProviderService.HasStableChapterID:input_type -> kiyomi.plugin.v1.HasStableChapterIDRequest
	28, // 28: kiyomi.plugin.v1.ContentProviderService.FetchChapters:input_type -> kiyomi.plugin.v1.FetchChaptersRequest
	30, // 29: kiyomi.plugin.v1.ContentProviderService.FetchPages:input_type -> kiyomi.plugin.v1.FetchPagesRequest
	32, // 30: kiyomi.plugin.v1.ContentProviderService.FetchPageStream:input_type -> kiyomi.plugin.v1.FetchPageStreamRequest
	34, // 31: kiyomi.plugin.v1.ContentProviderService.RateLimit:input_type -> kiyomi.plugin.v1.RateLimitRequest
	36, // 32: kiyomi.plugin.v1.TrackerService.Authenticate:input_type -> kiyomi.plugin.v1.AuthenticateRequest
	38, // 33: kiyomi.plugin.v1.TrackerService.PushProgress:input_type -> kiyomi.plugin.v1.PushProgressRequest
	40, // 34: kiyomi.plugin.v1.TrackerService.FetchProgress:input_type -> kiyomi.plugin.v1.FetchProgressRequest
	42, // 35: kiyomi.plugin.v1.TrackerService.IsAuthenticated:input_type -> kiyomi.plugin.v1.IsAuthenticatedRequest
	1,  // 36: kiyomi.plugin.v1.PluginService.Describe:output_type -> kiyomi.plugin.v1.DescribeResponse
	8,  // 37: kiyomi.plugin.v1.PluginService.Init:output_type -> kiyomi.plugin.v1.InitResponse
	19, // 38: kiyomi.plugin.v1.MetadataProviderService.Search:output_type -> kiyomi.plugin.v1.SearchResponse
	21, // 39: kiyomi.plugin.v1.MetadataProviderService.Details:output_type -> kiyomi.plugin.v1.DetailsResponse
	23, // 40: kiyomi.plugin.v1.MetadataProviderService.Cover:output_type -> kiyomi.plugin.v1.CoverResponse
	25, // 41: kiyomi.plugin.v1.MetadataProviderService.Aliases:output_type -> kiyomi.plugin.v1.AliasesResponse
	27, // 42: kiyomi.plugin.v1.ContentProviderService.HasStableChapterID:output_type -> kiyomi.plugin.v1.HasStableChapterIDResponse
	29, // 43: kiyomi.plugin.v1.ContentProviderService.FetchChapters:output_type -> kiyomi.plugin.v1.FetchChaptersResponse
	31, // 44: kiyomi.plugin.v1.ContentProviderService.FetchPages:output_type -> kiyomi.plugin.v1.FetchPagesResponse
	33, // 45: kiyomi.plugin.v1.ContentProviderService.FetchPageStream:output_type -> kiyomi.plugin.v1.FetchPageStreamResponse
	35, // 46: kiyomi.plugin.v1.ContentProviderService.RateLimit:output_type -> kiyomi.plugin.v1.RateLimitResponse
	37, // 47: kiyomi.plugin.v1.TrackerService.Authenticate:output_type -> kiyomi.plugin.v1.AuthenticateResponse
	39, // 48: kiyomi.plugin.v1.TrackerService.PushProgress:output_type -> kiyomi.plugin.v1.PushProgressResponse
	41, // 49: kiyomi.plugin.v1.TrackerService.FetchProgress:output_type -> kiyomi.plugin.v1.FetchProgressResponse
	43, // 50: kiyomi.plugin.v1.TrackerService.IsAuthenticated:output_type -> kiyomi.plugin.v1.IsAuthenticatedResponse
	36, // [36:51] is the sub-list for method output_type
	21, // [21:36] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
