// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: plugin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Describe_FullMethodName = "/kiyomi.plugin.v1.PluginService/Describe"
	PluginService_Init_FullMethodName     = "/kiyomi.plugin.v1.PluginService/Init"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService handles plugin metadata discovery and lifecycle initialization.
type PluginServiceClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, PluginService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, PluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService handles plugin metadata discovery and lifecycle initialization.
type PluginServiceServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	Init(context.Context, *InitRequest) (*InitResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiyomi.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginService_Describe_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _PluginService_Init_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	MetadataProviderService_Search_FullMethodName  = "/kiyomi.plugin.v1.MetadataProviderService/Search"
	MetadataProviderService_Details_FullMethodName = "/kiyomi.plugin.v1.MetadataProviderService/Details"
	MetadataProviderService_Cover_FullMethodName   = "/kiyomi.plugin.v1.MetadataProviderService/Cover"
	MetadataProviderService_Aliases_FullMethodName = "/kiyomi.plugin.v1.MetadataProviderService/Aliases"
)

// MetadataProviderServiceClient is the client API for MetadataProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataProviderService handles manga metadata search, details, covers, and aliases.
type MetadataProviderServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Details(ctx context.Context, in *DetailsRequest, opts ...grpc.CallOption) (*DetailsResponse, error)
	Cover(ctx context.Context, in *CoverRequest, opts ...grpc.CallOption) (*CoverResponse, error)
	Aliases(ctx context.Context, in *AliasesRequest, opts ...grpc.CallOption) (*AliasesResponse, error)
}

type metadataProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataProviderServiceClient(cc grpc.ClientConnInterface) MetadataProviderServiceClient {
	return &metadataProviderServiceClient{cc}
}

func (c *metadataProviderServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MetadataProviderService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderServiceClient) Details(ctx context.Context, in *DetailsRequest, opts ...grpc.CallOption) (*DetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetailsResponse)
	err := c.cc.Invoke(ctx, MetadataProviderService_Details_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderServiceClient) Cover(ctx context.Context, in *CoverRequest, opts ...grpc.CallOption) (*CoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoverResponse)
	err := c.cc.Invoke(ctx, MetadataProviderService_Cover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderServiceClient) Aliases(ctx context.Context, in *AliasesRequest, opts ...grpc.CallOption) (*AliasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliasesResponse)
	err := c.cc.Invoke(ctx, MetadataProviderService_Aliases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataProviderServiceServer is the server API for MetadataProviderService service.
// All implementations must embed UnimplementedMetadataProviderServiceServer
// for forward compatibility.
//
// MetadataProviderService handles manga metadata search, details, covers, and aliases.
type MetadataProviderServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Details(context.Context, *DetailsRequest) (*DetailsResponse, error)
	Cover(context.Context, *CoverRequest) (*CoverResponse, error)
	Aliases(context.Context, *AliasesRequest) (*AliasesResponse, error)
	mustEmbedUnimplementedMetadataProviderServiceServer()
}

// UnimplementedMetadataProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataProviderServiceServer struct{}

func (UnimplementedMetadataProviderServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMetadataProviderServiceServer) Details(context.Context, *DetailsRequest) (*DetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Details not implemented")
}
func (UnimplementedMetadataProviderServiceServer) Cover(context.Context, *CoverRequest) (*CoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cover not implemented")
}
func (UnimplementedMetadataProviderServiceServer) Aliases(context.Context, *AliasesRequest) (*AliasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Aliases not implemented")
}
func (UnimplementedMetadataProviderServiceServer) mustEmbedUnimplementedMetadataProviderServiceServer() {
}
func (UnimplementedMetadataProviderServiceServer) testEmbeddedByValue() {}

// UnsafeMetadataProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataProviderServiceServer will
// result in compilation errors.
type UnsafeMetadataProviderServiceServer interface {
	mustEmbedUnimplementedMetadataProviderServiceServer()
}

func RegisterMetadataProviderServiceServer(s grpc.ServiceRegistrar, srv MetadataProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataProviderService_ServiceDesc, srv)
}

func _MetadataProviderService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProviderService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProviderService_Details_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServiceServer).Details(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProviderService_Details_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServiceServer).Details(ctx, req.(*DetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProviderService_Cover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServiceServer).Cover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProviderService_Cover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServiceServer).Cover(ctx, req.(*CoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProviderService_Aliases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServiceServer).Aliases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProviderService_Aliases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServiceServer).Aliases(ctx, req.(*AliasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataProviderService_ServiceDesc is the grpc.ServiceDesc for MetadataProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiyomi.plugin.v1.MetadataProviderService",
	HandlerType: (*MetadataProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _MetadataProviderService_Search_Handler,
		},
		{
			MethodName: "Details",
			Handler:    _MetadataProviderService_Details_Handler,
		},
		{
			MethodName: "Cover",
			Handler:    _MetadataProviderService_Cover_Handler,
		},
		{
			MethodName: "Aliases",
			Handler:    _MetadataProviderService_Aliases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	ContentProviderService_HasStableChapterID_FullMethodName = "/kiyomi.plugin.v1.ContentProviderService/HasStableChapterID"
	ContentProviderService_FetchChapters_FullMethodName      = "/kiyomi.plugin.v1.ContentProviderService/FetchChapters"
	ContentProviderService_FetchPages_FullMethodName         = "/kiyomi.plugin.v1.ContentProviderService/FetchPages"
	ContentProviderService_FetchPageStream_FullMethodName    = "/kiyomi.plugin.v1.ContentProviderService/FetchPageStream"
	ContentProviderService_RateLimit_FullMethodName          = "/kiyomi.plugin.v1.ContentProviderService/RateLimit"
)

// ContentProviderServiceClient is the client API for ContentProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContentProviderService handles chapter discovery, page lists, and page image streaming.
type ContentProviderServiceClient interface {
	HasStableChapterID(ctx context.Context, in *HasStableChapterIDRequest, opts ...grpc.CallOption) (*HasStableChapterIDResponse, error)
	FetchChapters(ctx context.Context, in *FetchChaptersRequest, opts ...grpc.CallOption) (*FetchChaptersResponse, error)
	FetchPages(ctx context.Context, in *FetchPagesRequest, opts ...grpc.CallOption) (*FetchPagesResponse, error)
	FetchPageStream(ctx context.Context, in *FetchPageStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchPageStreamResponse], error)
	RateLimit(ctx context.Context, in *RateLimitRequest, opts ...grpc.CallOption) (*RateLimitResponse, error)
}

type contentProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentProviderServiceClient(cc grpc.ClientConnInterface) ContentProviderServiceClient {
	return &contentProviderServiceClient{cc}
}

func (c *contentProviderServiceClient) HasStableChapterID(ctx context.Context, in *HasStableChapterIDRequest, opts ...grpc.CallOption) (*HasStableChapterIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasStableChapterIDResponse)
	err := c.cc.Invoke(ctx, ContentProviderService_HasStableChapterID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProviderServiceClient) FetchChapters(ctx context.Context, in *FetchChaptersRequest, opts ...grpc.CallOption) (*FetchChaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchChaptersResponse)
	err := c.cc.Invoke(ctx, ContentProviderService_FetchChapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProviderServiceClient) FetchPages(ctx context.Context, in *FetchPagesRequest, opts ...grpc.CallOption) (*FetchPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPagesResponse)
	err := c.cc.Invoke(ctx, ContentProviderService_FetchPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProviderServiceClient) FetchPageStream(ctx context.Context, in *FetchPageStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchPageStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContentProviderService_ServiceDesc.Streams[0], ContentProviderService_FetchPageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchPageStreamRequest, FetchPageStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentProviderService_FetchPageStreamClient = grpc.ServerStreamingClient[FetchPageStreamResponse]

func (c *contentProviderServiceClient) RateLimit(ctx context.Context, in *RateLimitRequest, opts ...grpc.CallOption) (*RateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateLimitResponse)
	err := c.cc.Invoke(ctx, ContentProviderService_RateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentProviderServiceServer is the server API for ContentProviderService service.
// All implementations must embed UnimplementedContentProviderServiceServer
// for forward compatibility.
//
// ContentProviderService handles chapter discovery, page lists, and page image streaming.
type ContentProviderServiceServer interface {
	HasStableChapterID(context.Context, *HasStableChapterIDRequest) (*HasStableChapterIDResponse, error)
	FetchChapters(context.Context, *FetchChaptersRequest) (*FetchChaptersResponse, error)
	FetchPages(context.Context, *FetchPagesRequest) (*FetchPagesResponse, error)
	FetchPageStream(*FetchPageStreamRequest, grpc.ServerStreamingServer[FetchPageStreamResponse]) error
	RateLimit(context.Context, *RateLimitRequest) (*RateLimitResponse, error)
	mustEmbedUnimplementedContentProviderServiceServer()
}

// UnimplementedContentProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentProviderServiceServer struct{}

func (UnimplementedContentProviderServiceServer) HasStableChapterID(context.Context, *HasStableChapterIDRequest) (*HasStableChapterIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasStableChapterID not implemented")
}
func (UnimplementedContentProviderServiceServer) FetchChapters(context.Context, *FetchChaptersRequest) (*FetchChaptersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchChapters not implemented")
}
func (UnimplementedContentProviderServiceServer) FetchPages(context.Context, *FetchPagesRequest) (*FetchPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchPages not implemented")
}
func (UnimplementedContentProviderServiceServer) FetchPageStream(*FetchPageStreamRequest, grpc.ServerStreamingServer[FetchPageStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchPageStream not implemented")
}
func (UnimplementedContentProviderServiceServer) RateLimit(context.Context, *RateLimitRequest) (*RateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateLimit not implemented")
}
func (UnimplementedContentProviderServiceServer) mustEmbedUnimplementedContentProviderServiceServer() {
}
func (UnimplementedContentProviderServiceServer) testEmbeddedByValue() {}

// UnsafeContentProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentProviderServiceServer will
// result in compilation errors.
type UnsafeContentProviderServiceServer interface {
	mustEmbedUnimplementedContentProviderServiceServer()
}

func RegisterContentProviderServiceServer(s grpc.ServiceRegistrar, srv ContentProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedContentProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentProviderService_ServiceDesc, srv)
}

func _ContentProviderService_HasStableChapterID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasStableChapterIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProviderServiceServer).HasStableChapterID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProviderService_HasStableChapterID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProviderServiceServer).HasStableChapterID(ctx, req.(*HasStableChapterIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProviderService_FetchChapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchChaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProviderServiceServer).FetchChapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProviderService_FetchChapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProviderServiceServer).FetchChapters(ctx, req.(*FetchChaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProviderService_FetchPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProviderServiceServer).FetchPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProviderService_FetchPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProviderServiceServer).FetchPages(ctx, req.(*FetchPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProviderService_FetchPageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchPageStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContentProviderServiceServer).FetchPageStream(m, &grpc.GenericServerStream[FetchPageStreamRequest, FetchPageStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentProviderService_FetchPageStreamServer = grpc.ServerStreamingServer[FetchPageStreamResponse]

func _ContentProviderService_RateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProviderServiceServer).RateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProviderService_RateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProviderServiceServer).RateLimit(ctx, req.(*RateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentProviderService_ServiceDesc is the grpc.ServiceDesc for ContentProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiyomi.plugin.v1.ContentProviderService",
	HandlerType: (*ContentProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasStableChapterID",
			Handler:    _ContentProviderService_HasStableChapterID_Handler,
		},
		{
			MethodName: "FetchChapters",
			Handler:    _ContentProviderService_FetchChapters_Handler,
		},
		{
			MethodName: "FetchPages",
			Handler:    _ContentProviderService_FetchPages_Handler,
		},
		{
			MethodName: "RateLimit",
			Handler:    _ContentProviderService_RateLimit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchPageStream",
			Handler:       _ContentProviderService_FetchPageStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	TrackerService_Authenticate_FullMethodName    = "/kiyomi.plugin.v1.TrackerService/Authenticate"
	TrackerService_PushProgress_FullMethodName    = "/kiyomi.plugin.v1.TrackerService/PushProgress"
	TrackerService_FetchProgress_FullMethodName   = "/kiyomi.plugin.v1.TrackerService/FetchProgress"
	TrackerService_IsAuthenticated_FullMethodName = "/kiyomi.plugin.v1.TrackerService/IsAuthenticated"
)

// TrackerServiceClient is the client API for TrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TrackerService handles external reading progress synchronization and authentication.
type TrackerServiceClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	PushProgress(ctx context.Context, in *PushProgressRequest, opts ...grpc.CallOption) (*PushProgressResponse, error)
	FetchProgress(ctx context.Context, in *FetchProgressRequest, opts ...grpc.CallOption) (*FetchProgressResponse, error)
	IsAuthenticated(ctx context.Context, in *IsAuthenticatedRequest, opts ...grpc.CallOption) (*IsAuthenticatedResponse, error)
}

type trackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackerServiceClient(cc grpc.ClientConnInterface) TrackerServiceClient {
	return &trackerServiceClient{cc}
}

func (c *trackerServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, TrackerService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) PushProgress(ctx context.Context, in *PushProgressRequest, opts ...grpc.CallOption) (*PushProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushProgressResponse)
	err := c.cc.Invoke(ctx, TrackerService_PushProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) FetchProgress(ctx context.Context, in *FetchProgressRequest, opts ...grpc.CallOption) (*FetchProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchProgressResponse)
	err := c.cc.Invoke(ctx, TrackerService_FetchProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) IsAuthenticated(ctx context.Context, in *IsAuthenticatedRequest, opts ...grpc.CallOption) (*IsAuthenticatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAuthenticatedResponse)
	err := c.cc.Invoke(ctx, TrackerService_IsAuthenticated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackerServiceServer is the server API for TrackerService service.
// All implementations must embed UnimplementedTrackerServiceServer
// for forward compatibility.
//
// TrackerService handles external reading progress synchronization and authentication.
type TrackerServiceServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	PushProgress(context.Context, *PushProgressRequest) (*PushProgressResponse, error)
	FetchProgress(context.Context, *FetchProgressRequest) (*FetchProgressResponse, error)
	IsAuthenticated(context.Context, *IsAuthenticatedRequest) (*IsAuthenticatedResponse, error)
	mustEmbedUnimplementedTrackerServiceServer()
}

// UnimplementedTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackerServiceServer struct{}

func (UnimplementedTrackerServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedTrackerServiceServer) PushProgress(context.Context, *PushProgressRequest) (*PushProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushProgress not implemented")
}
func (UnimplementedTrackerServiceServer) FetchProgress(context.Context, *FetchProgressRequest) (*FetchProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchProgress not implemented")
}
func (UnimplementedTrackerServiceServer) IsAuthenticated(context.Context, *IsAuthenticatedRequest) (*IsAuthenticatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsAuthenticated not implemented")
}
func (UnimplementedTrackerServiceServer) mustEmbedUnimplementedTrackerServiceServer() {}
func (UnimplementedTrackerServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackerServiceServer will
// result in compilation errors.
type UnsafeTrackerServiceServer interface {
	mustEmbedUnimplementedTrackerServiceServer()
}

func RegisterTrackerServiceServer(s grpc.ServiceRegistrar, srv TrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackerService_ServiceDesc, srv)
}

func _TrackerService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_PushProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).PushProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_PushProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).PushProgress(ctx, req.(*PushProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_FetchProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).FetchProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_FetchProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).FetchProgress(ctx, req.(*FetchProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_IsAuthenticated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthenticatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).IsAuthenticated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_IsAuthenticated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).IsAuthenticated(ctx, req.(*IsAuthenticatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackerService_ServiceDesc is the grpc.ServiceDesc for TrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiyomi.plugin.v1.TrackerService",
	HandlerType: (*TrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _TrackerService_Authenticate_Handler,
		},
		{
			MethodName: "PushProgress",
			Handler:    _TrackerService_PushProgress_Handler,
		},
		{
			MethodName: "FetchProgress",
			Handler:    _TrackerService_FetchProgress_Handler,
		},
		{
			MethodName: "IsAuthenticated",
			Handler:    _TrackerService_IsAuthenticated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
